platform: ipq: Resolve unused variable warnings
This change resolves the below warnings

drivers/platform/ipq/sec-upgrade.c: In function
'store_sec_auth':
drivers/platform/ipq/sec-upgrade.c:351:22: error: unused variable 'st'
[-Werror=unused-variable] 351 | 	struct kstat st;

drivers/platform/ipq/sec-upgrade.c:350:22: error: unused variable 'file'
[-Werror=unused-variable] 350 |         struct file *file;

Change-Id: I5165d66012661571c1a7174c8591f8c86a6820cf
Signed-off-by: Devi Priya <quic_devipriy@quicinc.com>