arm64: dts: qcom: Update the PCIE3 configuration for RDP475-C1
This patch updates the pcie3 to GEN2 and sets the link retry
count to 400 for the pci link up and also removes the unused
entries in RDP475-C1 dts

The new property serdes-reg-update is introduced to update
on top of the default serdes PHY configuration

The vendor id is updated to 0x9022 to mark the PCIe is gen2x2
previously 0x9021 is for gen2x1.

When including the qcom-fpga-pci.h header file in other subsystem,
the below build error is seen to resolve this the regmap header file
is included in qcom-fpga-pci.h

./include/linux/qcom-fpga-pci.h:25:44: error: 'struct reg_sequence'
declared inside parameter list will not be visible outside of this
definition or declaration [-Werror]
   25 | int qcom_fpga_multi_reg_write(const struct reg_sequence *regs,
      |                                            ^~~~~~~~~~~~
./include/linux/qcom-fpga-pci.h:27:37: error: 'struct reg_sequence'
declared inside parameter list will not be visible outside of this
definition or declaration [-Werror]
   27 | int qcom_fpga_multi_reg_read(struct reg_sequence *regs,
      |                                     ^~~~~~~~~~~~
int num_regs);

Change-Id: I16a8c3ebb4bd0b2fdabfe49ba530c432f53f718e
Signed-off-by: Timple Raj M <quic_timple@quicinc.com>