bus: mhi: fuse_blower: fix the -Werror=unused-result warning
drivers/bus/mhi/fuse_blower/mhi_fuse_blower.c:513:17: error: ignoring return value of 'sysfs_create_file' declared with attribute 'warn_unused_result' [-Werror=unused-result]

Change-Id: I3b6bcb5d441fc7608f276d9b74a5a40395f82522
Signed-off-by: Kathiravan Thirumoorthy <quic_kathirav@quicinc.com>